### ISSUE TITLE
Setup weak AI base construction plan

### ISSUE THREAD

**Issue by WoodardEric** [Brett208/OP2MissionOutOfTheFryingPan#6]

**Comment by Brett208** [comment]
Make sure all added buildings are added to the construction group so they are rebuilt if destroyed.

**Buildings to add:**

* Second Smelter
* Residence
* Agridome
* Medical Center
* Second Tokamak
* DIRT
* Guard Post Clusters (x1 EMP, x1 Stickyfoam, x1 ESG)
  * Surround Base

**Add for construction**
* DIRT (x2)
* Residence
* Agridome
* Medical Center
